version: "3.8"
services:
  frontend:
    build: ./systeminfo_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

  backend:
    build: ./systeminfo_backend
    ports:
      - "3010:3010"
